version: '3.8'

services:
  python-app:
    build: .
    container_name: investEye
    volumes:
      - .:/app
    command: python main.py
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
        - FINNHUB_API_KEY=${FINNHUB_API_KEY}
