name: Deploy to Self-Hosted Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop old containers
        run: docker-compose down

      - name: Write envfile file
        run: |
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> envfile
          echo "FINNHUB_API_KEY=${{ secrets.FINNHUB_API_KEY }}" >> envfile

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Cleanup dangling images (optional)
        run: docker image prune -f
